### ISSUE TITLE
AssertionError: No dataset found at C:\Users\Admin\1video_enhancevrt\VRT\custom\

### ISSUE THREAD

**Issue by maheshs11** [JingyunLiang/VRT#11]
![image](https://user-images.githubusercontent.com/7268915/153872040-1d259902-c679-41ea-a86b-c2e7185ae0e4.png)

**Comment by maheshs11** [comment]
my laptop got stuck , i have 1650 graphic card and 8 gb ram ,is it not possible to run with this config?

in colab also i am getting memory limitation issue.

and also can u check this code it is not creating .png files when i upload a video.?

 if not filename.split('.')[-1].lower() in ['png','jpeg','jpg','tiff','bmp','tif',]: # image or video
    print(f'extracting the video as frames to {input_folder}')
    os.system(f'ffmpeg -i testsets/uploaded/{filename} -qscale:v 1 -qmin 1 -qmax 1 -vsync 0  {input_folder}/frame%08d.png')
!ls testsets/uploaded

**Comment by JingyunLiang** [comment]
1, The code only supports cuda. Testing it on a laptop without cuda (only 8 gb RAM) may not work.
2, In Colab, you can use smaller `--tile 6 128 128` if OOM. (Uploading too large video will lead to OOM as well because the video itself consumes much memory)
3, The Colab bug is fixed. You can upload a video to test it now.
